import type { RepositoryAnalysis } from "@/lib/contracts";
import {
  buildContributors,
  buildMilestones,
  buildSnapshots,
  type CommitInput,
  type TreeInput,
} from "@/lib/analyzer";

const points = [
  {
    date: "2023-02-14T10:00:00Z",
    sha: "13af091",
    message: "Initial editor prototype",
    paths: [
      "README.md",
      "package.json",
      "src/app.tsx",
      "src/editor.tsx",
      "src/styles.css",
    ],
  },
  {
    date: "2023-09-03T10:00:00Z",
    sha: "4bb7c32",
    message: "Add collaborative documents",
    paths: [
      "README.md",
      "package.json",
      "src/app.tsx",
      "src/editor/canvas.tsx",
      "src/editor/toolbar.tsx",
      "src/editor/history.ts",
      "src/styles.css",
      "src/collaboration/presence.ts",
      "src/collaboration/sync.ts",
      "src/api/documents.ts",
    ],
  },
  {
    date: "2024-04-18T10:00:00Z",
    sha: "8d92ed1",
    message: "Extract rendering engine",
    paths: [
      "README.md",
      "package.json",
      "apps/web/app.tsx",
      "apps/web/styles.css",
      "packages/editor/canvas.tsx",
      "packages/editor/toolbar.tsx",
      "packages/editor/history.ts",
      "packages/collaboration/presence.ts",
      "packages/collaboration/sync.ts",
      "packages/engine/renderer.ts",
      "packages/engine/geometry.ts",
      "packages/engine/viewport.ts",
      "services/api/documents.ts",
    ],
  },
  {
    date: "2025-01-11T10:00:00Z",
    sha: "bd740e8",
    message: "Launch plugin architecture",
    paths: [
      "README.md",
      "package.json",
      "apps/web/app.tsx",
      "apps/web/styles.css",
      "packages/editor/canvas.tsx",
      "packages/editor/toolbar.tsx",
      "packages/editor/history.ts",
      "packages/collaboration/presence.ts",
      "packages/collaboration/sync.ts",
      "packages/engine/renderer.ts",
      "packages/engine/geometry.ts",
      "packages/engine/viewport.ts",
      "packages/plugins/api.ts",
      "packages/plugins/registry.ts",
      "packages/plugins/sandbox.ts",
      "services/api/documents.ts",
      "services/api/plugins.ts",
    ],
  },
  {
    date: "2026-07-28T10:00:00Z",
    sha: "f10a9c2",
    message: "Harden offline-first workspace",
    paths: [
      "README.md",
      "package.json",
      "apps/web/app.tsx",
      "apps/web/styles.css",
      "apps/web/offline.ts",
      "packages/editor/canvas.tsx",
      "packages/editor/toolbar.tsx",
      "packages/editor/history.ts",
      "packages/collaboration/presence.ts",
      "packages/collaboration/sync.ts",
      "packages/engine/renderer.ts",
      "packages/engine/geometry.ts",
      "packages/engine/viewport.ts",
      "packages/plugins/api.ts",
      "packages/plugins/registry.ts",
      "packages/plugins/sandbox.ts",
      "packages/storage/indexed-db.ts",
      "packages/storage/reconcile.ts",
      "services/api/documents.ts",
      "services/api/plugins.ts",
    ],
  },
];

const trees: TreeInput[] = points.map((point, pointIndex) => ({
  sha: point.sha,
  date: point.date,
  message: point.message,
  truncated: false,
  entries: point.paths.map((path, index) => ({
    path,
    type: "blob",
    size: 700 + pointIndex * 311 + index * 173,
  })),
}));
const commits: CommitInput[] = Array.from({ length: 32 }, (_, index) => ({
  sha: `demo${index.toString().padStart(3, "0")}`,
  date: new Date(
    Date.UTC(2023 + Math.floor(index / 10), index % 12, 1),
  ).toISOString(),
  message: `Demo change ${index + 1}`,
  author: ["Maya Chen", "Noah Williams", "Priya Shah", "Leo Martin"][index % 4],
  treeSha: `tree${index}`,
}));
const snapshots = buildSnapshots(trees);

export const demoAnalysis: RepositoryAnalysis = {
  schemaVersion: "1.0",
  repository: {
    owner: "time-machine-labs",
    name: "canvas",
    fullName: "time-machine-labs/canvas",
    description:
      "A fictional collaborative canvas used to demonstrate deterministic repository analysis.",
    url: "https://github.com/time-machine-labs/canvas",
    defaultBranch: "main",
    primaryLanguage: "TypeScript",
    stars: 0,
    forks: 0,
    updatedAt: points.at(-1)!.date,
  },
  summary: {
    sampledCommits: commits.length,
    contributors: 4,
    filesAtHead: snapshots.at(-1)!.totalFiles,
    firstSampledAt: points[0].date,
    lastSampledAt: points.at(-1)!.date,
  },
  snapshots,
  contributors: buildContributors(commits),
  milestones: buildMilestones(snapshots),
  coverage: {
    historyLimit: 60,
    snapshotCount: snapshots.length,
    fileLimitPerSnapshot: 1500,
    partial: true,
    reasons: [
      "This built-in demo uses a fictional, clearly labeled repository history.",
    ],
  },
};
